apiVersion: v1
kind: Secret
metadata:
  name: finmark-secrets
  namespace: finmark
type: Opaque
stringData:
  POSTGRES_DB: finmark_orders
  POSTGRES_USER: finmark_order
  POSTGRES_PASSWORD: replace-with-demo-password
  DATABASE_URL: postgresql://finmark_order:replace-with-demo-password@order-db:5432/finmark_orders
  SECRET_KEY: replace-with-a-long-random-secret
  PASSWORD_SALT: replace-with-a-random-salt
  TOKEN_ALGORITHM: HS256