import os
from typing import Any

import psycopg
from psycopg.rows import dict_row


DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://finmark_order:finmark_order_demo_password"
    "@localhost:5433/finmark_orders",
)


SERVICE_SEED_DATA = [
    (
        1,
        "Financial Analysis",
        25000.00,
        "Finance",
        "Detailed financial analysis for business decision-making.",
    ),
    (
        2,
        "Marketing Analytics",
        30000.00,
        "Marketing",
        "Customer, market, and campaign performance analysis.",
    ),
    (
        3,
        "Business Intelligence",
        40000.00,
        "Business Intelligence",
        "Business dashboards, reports, and operational insights.",
    ),
    (
        4,
        "Consulting Services",
        35000.00,
        "Consulting",
        "Strategic consulting services for small and medium enterprises.",
    ),
]


def get_connection() -> psycopg.Connection:
    """Create a new PostgreSQL connection."""

    return psycopg.connect(
        DATABASE_URL,
        row_factory=dict_row,
    )


def initialize_database() -> None:
    """Create the Order Service tables and seed the service catalog."""

    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS service_catalog (
                    id INTEGER PRIMARY KEY,
                    name VARCHAR(120) NOT NULL,
                    base_price NUMERIC(12, 2) NOT NULL,
                    category VARCHAR(120) NOT NULL,
                    description TEXT NOT NULL,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE
                )
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS service_orders (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_name VARCHAR(120) NOT NULL,
                    customer_email VARCHAR(255) NOT NULL,
                    client_type VARCHAR(80) NOT NULL,
                    service_id INTEGER NOT NULL
                        REFERENCES service_catalog(id),
                    service_name VARCHAR(120) NOT NULL,
                    base_price NUMERIC(12, 2) NOT NULL,
                    order_notes TEXT NOT NULL DEFAULT '',
                    status VARCHAR(30) NOT NULL DEFAULT 'pending',
                    handled_by_instance VARCHAR(255) NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """
            )

            cursor.executemany(
                """
                INSERT INTO service_catalog (
                    id,
                    name,
                    base_price,
                    category,
                    description
                )
                VALUES (%s, %s, %s, %s, %s)
                ON CONFLICT (id) DO UPDATE SET
                    name = EXCLUDED.name,
                    base_price = EXCLUDED.base_price,
                    category = EXCLUDED.category,
                    description = EXCLUDED.description,
                    is_active = TRUE
                """,
                SERVICE_SEED_DATA,
            )


def check_database() -> bool:
    """Check whether PostgreSQL accepts a simple query."""

    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute("SELECT 1")
            result = cursor.fetchone()

    return result is not None


def get_service_catalog() -> list[dict[str, Any]]:
    """Return all active FinMark services."""

    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    id,
                    name,
                    base_price,
                    category,
                    description,
                    is_active
                FROM service_catalog
                WHERE is_active = TRUE
                ORDER BY id
                """
            )

            return cursor.fetchall()


def create_order(
    customer_name: str,
    customer_email: str,
    client_type: str,
    service_id: int,
    order_notes: str,
    instance_id: str,
) -> dict[str, Any] | None:
    """Create a service order using a valid catalog service."""

    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT id, name, base_price
                FROM service_catalog
                WHERE id = %s
                  AND is_active = TRUE
                """,
                (service_id,),
            )

            service = cursor.fetchone()

            if service is None:
                return None

            cursor.execute(
                """
                INSERT INTO service_orders (
                    customer_name,
                    customer_email,
                    client_type,
                    service_id,
                    service_name,
                    base_price,
                    order_notes,
                    status,
                    handled_by_instance
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, 'pending', %s)
                RETURNING
                    id,
                    customer_name,
                    customer_email,
                    client_type,
                    service_id,
                    service_name,
                    base_price,
                    order_notes,
                    status,
                    handled_by_instance,
                    created_at
                """,
                (
                    customer_name,
                    customer_email,
                    client_type,
                    service["id"],
                    service["name"],
                    service["base_price"],
                    order_notes,
                    instance_id,
                ),
            )

            return cursor.fetchone()


def list_orders(limit: int = 100) -> list[dict[str, Any]]:
    """Return the most recent service orders."""

    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    id,
                    customer_name,
                    customer_email,
                    client_type,
                    service_id,
                    service_name,
                    base_price,
                    order_notes,
                    status,
                    handled_by_instance,
                    created_at
                FROM service_orders
                ORDER BY id DESC
                LIMIT %s
                """,
                (limit,),
            )

            return cursor.fetchall()


def get_order_summary() -> dict[str, Any]:
    """Return database-backed order totals."""

    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    COUNT(*) AS total_orders,
                    COUNT(*) FILTER (
                        WHERE status = 'pending'
                    ) AS pending_orders,
                    COUNT(*) FILTER (
                        WHERE status = 'processing'
                    ) AS processing_orders,
                    COUNT(*) FILTER (
                        WHERE status = 'completed'
                    ) AS completed_orders,
                    COALESCE(SUM(base_price), 0) AS projected_revenue
                FROM service_orders
                """
            )

            return cursor.fetchone()